name: Check the source code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint